# Copyright Contributors to the Open Cluster Management project

-include /opt/build-harness/Makefile.prow
-include Makefile
-include Makefile.dev

unit-tests: update-crds manifests generate fmt vet envtest ## Run tests.
	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)" go test $(shell go list ./... | grep -E -v "test") -coverprofile cover.out

.PHONY: build
build:
	go build -o bin/multiclusterhub-operator main.go