# Copyright Contributors to the Open Cluster Management project

.PHONY: update-manifest update-crds

deps:
	curl -sL https://github.com/operator-framework/operator-sdk/releases/download/v1.9.0/operator-sdk_darwin_amd64 -o bin/operator-sdk
	chmod +x bin/operator-sdk

update-crds:
	bash hack/scripts/gather-crds-dev.sh

subscriptions:
	oc apply -k hack/subscriptions

catalog:
	oc apply -k hack/catalog

prereqs:
	oc apply -k hack/prereqs

copyright:
	bash ./hack/scripts/copyright.sh

update-version:
	./hack/scripts/update-version.sh <START_VERSION> <UPDATE_VERSION>

prep-mock-install:
	export PRODUCT_VERSION=$(shell cat COMPONENT_VERSION); \
	make mock-build-image PRODUCT_VERSION=$(VERSION) MOCK_IMAGE_REGISTRY=$(REGISTRY) MOCK_IMAGE_SHA="sha256:test"
	echo "mock install prepped!"

regenerate-operator-bundles: ## Regenerates the operator bundles
	pip install -r hack/bundle-automation/requirements.txt
	python3 ./hack/bundle-automation/generate-bundles.py --destination pkg/templates/

# different from `in-cluster-install` (call update-crds, no secrets, no observability-crd)
mock-install: prereqs subscriptions update-crds  docker-build docker-push deploy

cr: 
	oc apply -k config/samples


## Ensure the quay repos are open or pull secrets are configured
full-catalog-install: manifests generate bundle bundle-build bundle-push catalog-build catalog-push prereqs subscriptions catalog

full-dev-install: prereqs manifests generate update-manifest update-crds subscriptions docker-build docker-push deploy

add-images: ## Retrieves latest manifest and injects image definitions directly into the deployment template
	pip3 install -r ./hack/bundle-automation/requirements.txt
	python3 ./hack/scripts/dev-update-image-references.py

add-images-local:  ## Generates a local image manifest. Source this file to define necessary environment variables to run the operator locally
	pip3 install -r ./hack/bundle-automation/requirements.txt
	python3 ./hack/scripts/dev-update-image-references.py --local