apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnTemplate
metadata:
  name: mtv-operator
spec:
  addonName: mtv-operator
  agentSpec:
    workload:
      manifests:
      - apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: mtv-operator
          namespace: open-cluster-management-policies
        spec:
          complianceType: musthave
          operatorGroup:
            name: openshift-mtv
            namespace: openshift-mtv
            targetNamespaces:
            - openshift-mtv
          remediationAction: enforce
          subscription:
            channel: dev-preview
            name: mtv-operator
            namespace: openshift-mtv
            source: mtv-extra-catalog-source
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
      - apiVersion: forklift.konveyor.io/v1beta1
        kind: ForkliftController
        metadata:
          name: forklift-controller
          namespace: openshift-mtv
        spec:
          feature_ocp_live_migration: 'true'
          feature_ui_plugin: 'true'
          feature_validation: 'true'
          feature_volume_populator: 'true'
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: mtv-integrations
        spec: {}
