apiVersion: rbac.open-cluster-management.io/v1beta1
kind: MulticlusterRoleAssignment
metadata:
  name: mtv-advisor-storageclasses
  namespace: '{{ default "open-cluster-management" .Values.global.namespace }}'
spec:
  roleAssignments:
  - clusterRole: acm-vm-extended:admin
    clusterSelection:
      placements:
      - name: openshift-cnv
        namespace: '{{ default "open-cluster-management" .Values.global.namespace }}'
      type: placements
    name: acm-vm-extended-admin
  subject:
    kind: ServiceAccount
    name: mtv-integrations-manager
    namespace: '{{ default "open-cluster-management" .Values.global.namespace }}'
