# Copyright Contributors to the Open Cluster Management project

CURL ?= curl
HELMFILE ?= helmfile

## Install helmfile
helmfile/install: packages/install/helmfile packages/install/kubectl packages/install/helm
	@exit 0


