{{- if .Values.global.networkPolicies.enabled }}
# Copyright Contributors to the Open Cluster Management project

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: insights-metrics-network-policy
  labels:
    app: {{ .Chart.Name }}
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    component: insights-metrics
    release: {{ .Chart.Name }}
    heritage: release-service
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: "insights-metrics"
      release: {{ .Chart.Name }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-monitoring
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-ingress
    ports:
    - port: 8443
      protocol: TCP
  policyTypes:
    - Ingress
{{- end }}
