#!/bin/bash

set -e

indent() {
  local INDENT="      "
  local INDENT1S="    -"
  sed -e "s/^/${INDENT}/" \
      -e "1s/^${INDENT}/${INDENT1S} /"
}

listCSV() {
  for index in ${!CSVDIRS[*]}
  do
    indent apiVersion < "$(ls "${CSVDIRS[$index]}"/*version.yaml)"
  done
}

addReqCRDs() {
  echo "required:" | sed 's/^/    /' >> ${DEPLOYDIR}/req_crds.yaml.bak
  for f in ${DEPLOYDIR}/req_crds/*; do ( cat "${f}"; echo) | sed 's/^/    /' >> ${DEPLOYDIR}/req_crds.yaml.bak; done
  sed -i'' -e "/customresourcedefinitions:/r ${DEPLOYDIR}/req_crds.yaml.bak" "${CSVFILE}"
}

unindent(){

  local FILENAME=$1
  local INDENT="    "
  local INDENT1S="- "

  if [[ "$OSTYPE" == "linux-gnu" ]]; then
    sed -i -e "1 s/${INDENT1S}/  /" "${FILENAME}"
    sed -i -e "s/${INDENT}//" "${FILENAME}"
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' -e "s/^${INDENT}//" "${FILENAME}"
    sed -i '' -e "s/^${INDENT1S}/  /" "${FILENAME}"
  fi
}

removeNamespacePlaceholder(){
  local FILENAME=$1
  if [[ "$OSTYPE" == "linux-gnu" ]]; then
    sed -e '/namespace: placeholder/d' "${FILENAME}"
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' -e '/namespace: placeholder/d' "${FILENAME}"
  fi
  
}

DEPLOYDIR=${DIR:-$(cd "$(dirname "$0")"/../../deploy && pwd)}
BUNDLE_REGISTRY=$1
IMG=$2
BUNDLE_VERSION=$(cat COMPONENT_VERSION)

export CSV_CHANNEL=alpha
export CSV_VERSION=0.0.1

cp "${DEPLOYDIR}"/operator.yaml "${DEPLOYDIR}"/operator.yaml.bak
if [ "$(uname)" = "Darwin" ]; then
  sed -i "" "s|multiclusterhub-operator:latest|${IMAGE}|g" "${DEPLOYDIR}"/operator.yaml
else
  sed -i "s|multiclusterhub-operator:latest|${IMAGE}|g" "${DEPLOYDIR}"/operator.yaml
fi

operator-sdk generate csv --csv-channel "${CSV_CHANNEL}" --csv-version "${CSV_VERSION}" --operator-name "${IMG}" >/dev/null 2>&1

cp "${DEPLOYDIR}"/operator.yaml.bak "${DEPLOYDIR}"/operator.yaml
rm -f "${DEPLOYDIR}"/operator.yaml.bak

BUILDDIR=${DIR:-$(cd "$(dirname "$0")"/../../build && pwd)}
OLMOUTPUTDIR="${BUILDDIR}"/_output/olm
mkdir -p "${OLMOUTPUTDIR}"

PKGDIR="${DEPLOYDIR}"/olm-catalog/multiclusterhub-operator
CSVDIRS[0]=${DIR:-$(cd "${PKGDIR}"/"${CSV_VERSION}" && pwd)}

CRD=$(grep -v -- "---" "$(ls "${DEPLOYDIR}"/crds/*crd.yaml)" | indent)
PKG=$(indent packageName < "$(ls "${PKGDIR}"/*multiclusterhub-operator.package.yaml)")
CSVFILE="${PKGDIR}"/"${CSV_VERSION}"/multiclusterhub-operator.v"${CSV_VERSION}".clusterserviceversion.yaml

# remove replaces field
sed -ie '/replaces:/d' "${CSVFILE}"

addReqCRDs
rm -f "${DEPLOYDIR}"/req_crds.yaml.bak
# disable all namespaces supported, see https://github.com/operator-framework/operator-sdk/issues/2173 
index=$(grep -n "type: AllNamespaces" "${CSVFILE}" | cut -d ":" -f 1)
index=$((index - 1))
if [ "$(uname)" = "Darwin" ]; then
  sed -i "" "${index}s/true/false/" "${CSVFILE}"
else
  sed -i "${index}s/true/false/" "${CSVFILE}"
fi

NAME=${NAME:-multiclusterhub-operator-registry}
NAMESPACE=${NAMESPACE:-multicloud-system}
DISPLAYNAME=${DISPLAYNAME:-multiclusterhub-operator}

cat <<< "$CRD" > "${OLMOUTPUTDIR}"/multiclusterhub.crd.yaml
cat <<< "$(listCSV)" > "${OLMOUTPUTDIR}"/multiclusterhub.csv.yaml

cat > "${OLMOUTPUTDIR}"/multiclusterhub.resources.yaml <<EOF | sed 's/^  *$//'
# This file was autogenerated by 'common/scripts/olm_catalog.sh'
# Do not edit it manually!
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: $NAME
spec:
  configMap: $NAME
  displayName: $DISPLAYNAME
  publisher: Red Hat
  sourceType: configmap
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: $NAME
data:
  customResourceDefinitions: |-
$(cat "${OLMOUTPUTDIR}"/multiclusterhub.crd.yaml)
  clusterServiceVersions: |-
$(cat "${OLMOUTPUTDIR}"/multiclusterhub.csv.yaml)
  packages: |-
$PKG
EOF

unindent "${OLMOUTPUTDIR}"/multiclusterhub.crd.yaml
unindent "${OLMOUTPUTDIR}"/multiclusterhub.csv.yaml
removeNamespacePlaceholder "${OLMOUTPUTDIR}"/multiclusterhub.csv.yaml

if [ ! -z ${TRAVIS_BRANCH+x} ]; then
cat <<EOF > "${OLMOUTPUTDIR}"/annotations.yaml
annotations:
  operators.operatorframework.io.bundle.mediatype.v1: "registry+v1"
  operators.operatorframework.io.bundle.manifests.v1: "manifests/"
  operators.operatorframework.io.bundle.metadata.v1: "metadata/"
  operators.operatorframework.io.bundle.package.v1: "$IMG-bundle"
  operators.operatorframework.io.bundle.channels.v1: "$CSV_CHANNEL"
  operators.operatorframework.io.bundle.channel.default.v1: "$CSV_CHANNEL"
EOF

  _IMAGE_REFERENCE=$BUNDLE_REGISTRY/$IMG:$BUNDLE_VERSION$COMPONENT_TAG_EXTENSION
  docker login $BUNDLE_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
  docker push $_IMAGE_REFERENCE
  _SHA_IMAGE_REFERENCE=$(docker inspect --format='{{index .RepoDigests 0}}' $_IMAGE_REFERENCE)
  if [ "$(uname)" = "Darwin" ]; then
    sed -i "" "s|quay.io/rhibmcollab/multiclusterhub-operator:latest|${_SHA_IMAGE_REFERENCE}|g" "${OLMOUTPUTDIR}"/multiclusterhub.csv.yaml
  else
    sed -i "s|quay.io/rhibmcollab/multiclusterhub-operator:latest|${_SHA_IMAGE_REFERENCE}|g" "${OLMOUTPUTDIR}"/multiclusterhub.csv.yaml
  fi

  cat "${OLMOUTPUTDIR}"/multiclusterhub.csv.yaml

  docker build --file "${BUILDDIR}"/Dockerfile.bundle \
    --build-arg OPERATOR_NAME=$IMG \
    --build-arg OPERATOR_CHANNELS=$CSV_CHANNEL \
    --build-arg OPERATOR_DEFAULT_CHANNEL=$CSV_CHANNEL \
    --build-arg OPERATOR_CRD="_output/olm/multiclusterhub.crd.yaml" \
    --build-arg OPERATOR_CSV="_output/olm/multiclusterhub.csv.yaml" \
    --build-arg ANNOTATION_YML="_output/olm/annotations.yaml" "${BUILDDIR}" -t $BUNDLE_REGISTRY/$IMG-bundle:$BUNDLE_VERSION$COMPONENT_TAG_EXTENSION

fi

\cp -r "${PKGDIR}" "${OLMOUTPUTDIR}"
rm -rf "${DEPLOYDIR}"/olm-catalog

rm -f ${OLMOUTPUTDIR}/*/*/*.yamle
rm -f ${OLMOUTPUTDIR}/*/*/*.yaml-e 

cp "${DEPLOYDIR}"/subscription.yaml "${OLMOUTPUTDIR}"
cp "${DEPLOYDIR}"/operator.yaml "${OLMOUTPUTDIR}"
cp "${DEPLOYDIR}"/crds/*_cr.yaml "${OLMOUTPUTDIR}"
cp "${DEPLOYDIR}"/kustomization.yaml "${OLMOUTPUTDIR}"

echo "Created ${OLMOUTPUTDIR}/annotations.yaml"
echo "Created ${OLMOUTPUTDIR}/multiclusterhub-operator"
echo "Created ${OLMOUTPUTDIR}/multiclusterhub.resources.yaml"
echo "Created ${OLMOUTPUTDIR}/multiclusterhub.crd.yaml"
echo "Created ${OLMOUTPUTDIR}/multiclusterhub.csv.yaml"
echo "Created ${OLMOUTPUTDIR}/operator.yaml"
echo "Created ${OLMOUTPUTDIR}/subscription.yaml"
echo "Created ${OLMOUTPUTDIR}/kustomization.yaml"
