#!/bin/bash

echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
echo "GITHUB_JOB: $GITHUB_JOB"
echo "GITHUB_ACTION: $GITHUB_ACTION"
echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
echo "GITHUB_SERVER_URL: $GITHUB_SERVER_URL"
echo "GITHUB_REF: $GITHUB_REF"

RESULTS_PATH=$1
RES=$(cat $RESULTS_PATH)
SLACK_MESSAGE="TESTS FAILED! :("
NOFAIL='failures="0"'
if [[ $RES == *$NOFAIL* ]]; 
then
    SLACK_MESSAGE="TESTS PASSED! :)"
fi
echo $SLACK_MESSAGE
curl -X POST -H 'Content-type: application/json' --data "{'text':'${SLACK_MESSAGE}'}" ${SLACKBOT_WEBHOOK_URL}