apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: dynamic-scoring-addon-config
  namespace: '{{ .Values.global.namespace }}'
spec:
  agentInstallNamespace: dynamic-scoring
  customizedVariables:
  - name: Image
    value: quay.io/open-cluster-management/dynamic-scoring-addon:latest
  - name: ImagePullSecrets
    value: '["hub-registry-secret"]'
