apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: dynamic-scoring-framework
spec:
  addOnMeta:
    description: Centralized scoring logic management and distribution agent for Open Cluster Management multi-cluster environments
    displayName: dynamic-scoring-framework
  installStrategy:
    placements:
    - configs:
      - group: addon.open-cluster-management.io
        name: dynamic-scoring-addon-config
        namespace: open-cluster-management
        resource: addondeploymentconfigs
      name: dynamic-scoring-placement
      namespace: '{{ default "open-cluster-management" .Values.global.namespace }}'
    - configs:
      - group: addon.open-cluster-management.io
        name: dynamic-scoring-addon-config-aarch64
        namespace: open-cluster-management
        resource: addondeploymentconfigs
      name: dynamic-scoring-placement-aarch64
      namespace: '{{ default "open-cluster-management" .Values.global.namespace }}'
    type: Placements
  supportedConfigs:
  - group: addon.open-cluster-management.io
    resource: addondeploymentconfigs
