{{- if .Values.global.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: alertmanager
  namespace: '{{ default "open-cluster-management-observability" .Values.global.namespace }}'
spec:
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: open-cluster-management-observability
      podSelector:
        matchLabels:
          app: multicluster-observability-alertmanager
    ports:
    - port: 9094
      protocol: TCP
    - port: 9094
      protocol: UDP
  - ports:
    - port: 9095
      protocol: TCP
    - port: 9096
      protocol: TCP
  podSelector:
    matchLabels:
      app: multicluster-observability-alertmanager
  policyTypes:
  - Ingress
  - Egress
{{- end }}
